=== mPunc/ToDoChecker/ToDoAPI/XmlData/to_do_list_items_dtd.dtd
<!ELEMENT ToDoListItems (ToDoListItem*)>
<!ATTLIST ToDoListItems
    xmlns:xsi CDATA #REQUIRED
    xmlns:xsd CDATA #REQUIRED>

<!ELEMENT ToDoListItem (Id, Title, TextContent, CreatedAt, DueDate, Priority)>
<!ATTLIST ToDoListItem
    completed CDATA #REQUIRED
    category CDATA #REQUIRED>

<!ELEMENT Id (#PCDATA)>
<!ELEMENT Title (#PCDATA)>
<!ELEMENT TextContent (MainText, Notes)>
<!ELEMENT MainText (#PCDATA)>
<!ELEMENT Notes (#PCDATA)>
<!ELEMENT CreatedAt (#PCDATA)>
<!ELEMENT DueDate (#PCDATA)>
<!ELEMENT Priority (#PCDATA)>

=== mPunc/ToDoChecker/Backend/ToDoAPI/XmlData/to_do_list_items_data.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ToDoListItems SYSTEM "to_do_list_items_dtd.dtd">
<ToDoListItems>
  <ToDoListItem completed="false" category="music">
    <Id>1</Id>
    <Title>Play guitar</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-09T08:11:35.0321684+02:00</CreatedAt>
    <DueDate>2025-05-11T08:11:35.0322892+02:00</DueDate>
    <Priority>high</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>3</Id>
    <Title>Go home</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-09T08:11:35.0321684+02:00</CreatedAt>
    <DueDate>2025-05-11T08:11:35.0322892+02:00</DueDate>
    <Priority>low</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>2</Id>
    <Title>Play guitar</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-08T23:49:05.3658913+02:00</CreatedAt>
    <DueDate>2025-05-10T23:49:05.365895+02:00</DueDate>
    <Priority>high</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>5</Id>
    <Title>Play guitarararar</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-08T23:49:05.3658913+02:00</CreatedAt>
    <DueDate>2025-05-10T23:49:05.365895+02:00</DueDate>
    <Priority>high</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>0</Id>
    <Title>Play guitar moreeeeeeeeeeeeeee</Title>
    <TextContent>
      <MainText>Test test, sviraj gitaru, ali ne na zakazivanje ostalih obaveza.</MainText>
      <Notes>test2</Notes>
    </TextContent>
    <CreatedAt>2025-05-09T02:05:01.6831327+02:00</CreatedAt>
    <DueDate>2025-05-11T02:05:01.6832821+02:00</DueDate>
    <Priority>low</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>4</Id>
    <Title>Go home</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes />
    </TextContent>
    <CreatedAt>2025-05-09T08:11:35.0321684+02:00</CreatedAt>
    <DueDate>2025-05-11T08:11:35.0322892+02:00</DueDate>
    <Priority>low</Priority>
  </ToDoListItem>
</ToDoListItems>

=== mPunc/ToDoChecker/ToDoAPI/XmlData/to_do_list_items_data.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE ToDoListItems SYSTEM "to_do_list_items_dtd.dtd">
<ToDoListItems>
  <ToDoListItem completed="false" category="music">
    <Id>0</Id>
    <Title>sleep</Title>
    <TextContent>
      <MainText>sleeping is important</MainText>
      <Notes />
    </TextContent>
    <CreatedAt>2025-05-09T08:33:21.0840665+02:00</CreatedAt>
    <DueDate>2025-05-11T08:33:21.0841928+02:00</DueDate>
    <Priority>medium</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>1</Id>
    <Title>Play guitar</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-09T08:11:35.0321684+02:00</CreatedAt>
    <DueDate>2025-05-11T08:11:35.0322892+02:00</DueDate>
    <Priority>high</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>4</Id>
    <Title>Go home</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-09T08:11:35.0321684+02:00</CreatedAt>
    <DueDate>2025-05-11T08:11:35.0322892+02:00</DueDate>
    <Priority>low</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>3</Id>
    <Title>Go home</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-09T08:11:35.0321684+02:00</CreatedAt>
    <DueDate>2025-05-11T08:11:35.0322892+02:00</DueDate>
    <Priority>low</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>2</Id>
    <Title>Play guitar</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-08T23:49:05.3658913+02:00</CreatedAt>
    <DueDate>2025-05-10T23:49:05.365895+02:00</DueDate>
    <Priority>high</Priority>
  </ToDoListItem>
  <ToDoListItem completed="false" category="music">
    <Id>5</Id>
    <Title>Play guitarararar</Title>
    <TextContent>
      <MainText>asdasdasd</MainText>
      <Notes>asdfafa</Notes>
    </TextContent>
    <CreatedAt>2025-05-08T23:49:05.3658913+02:00</CreatedAt>
    <DueDate>2025-05-10T23:49:05.365895+02:00</DueDate>
    <Priority>high</Priority>
  </ToDoListItem>
</ToDoListItems>
